Output gif_demo/demo.gif

Require leetui

Set Shell fish
Sleep 500ms
Type "leetui"
Enter
Sleep 1.5s
Down 3
Up 3
Sleep 500ms
Type "tt"
Sleep 500ms
Type "TT"
Sleep 1.5s
Enter
Sleep 500ms
Down 4
Sleep 500ms
Up 4
Escape
Sleep 2s
Type "e"
Sleep 1.5s
Down 3
Enter
Sleep 3.5s
Escape
Type ":wq"
Enter
Sleep 1.5s
Type "r"
Sleep 500ms
Enter
Sleep 5s
Enter
Sleep 1.5s
Type "s"
Sleep 500ms
Enter
Sleep 4s
Enter
Sleep 500ms
Ctrl+S
Sleep 1.5s
Enter
Sleep 1s
