//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

pub mod prelude;
pub mod question;
pub mod question_topic_tag;
pub mod topic_tag;

pub type QuestionModel = question::Model;
pub type TopicTagModel = topic_tag::Model;
pub type QuestionEntity = question::Entity;
pub type TopicTagEntity = topic_tag::Entity;
