//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

pub use super::question::Entity as Question;
pub use super::question_topic_tag::Entity as QuestionTopicTag;
pub use super::topic_tag::Entity as TopicTag;
