//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "QuestionTopicTag")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub question_id: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub tag_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::question::Entity",
        from = "Column::QuestionId",
        to = "super::question::Column::FrontendQuestionId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Question,
    #[sea_orm(
        belongs_to = "super::topic_tag::Entity",
        from = "Column::TagId",
        to = "super::topic_tag::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    TopicTag,
}

impl Related<super::question::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Question.def()
    }
}

impl Related<super::topic_tag::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TopicTag.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
